# Generated by Django 5.0 on 2025-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
