# Generated by Django 5.0 on 2025-09-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-sold', 'name']},
        ),
    ]
